#!/bin/sh
[ "$1" ] || exit 1
for s in "$@"; do
    if ! [ -d "/run/service/$s/" ]; then
        echo "ERROR: Missing service dir /run/service/$s/" >&2
        continue
    fi
    s6-svc -o "/run/service/$s"
done
