#!/bin/sh
[ "$1" ] || exit 1
for s in "$@"; do
    if ! [ -d "/run/s6/services/$s/" ]; then
        echo "ERROR: Missing service dir /run/s6/services/$s/" >&2
        continue
    fi
    rm "/run/s6/services/$s/down"
    s6-svc -u "/run/s6/services/$s"
done
