#!/bin/sh

ver=$(echo "${CACHE_TAG}"|cut -d- -f2)
if [ "$ver" ]; then
    ver="-$ver"
fi

echo "## Building layers for tag '$CACHE_TAG' and version '$ver'"

for layer in base dbipc python3; do
    echo "############################################################"
    echo "### building layer '$layer'"
    echo "### $ docker build --build-arg TAGVER=$ver"
    echo "### >  -t $DOCKER_REPO:$layer $layer/"
    echo "############################################################"

    docker build --build-arg "TAGVER=$ver" -t $DOCKER_REPO:$layer "$layer/"
    res=$?
    if [ $res -ne 0 ]; then
        echo "Building layer $layer returned $res" >&2
        exit $res
    fi
    if [ "$ver" ]; then
        docker tag $DOCKER_REPO:$layer $DOCKER_REPO:$layer$ver
    fi
done
