FROM apluslms/service-base:dbipc

COPY rootfs /

RUN apt_install \
    build-essential \
    python3-dev \
    python3 \
    python3-certifi \
    python3-pip \
    python3-virtualenv \
    python3-setuptools \
    python3-wheel \
    python3-gunicorn \
    python3-psycopg2
    

