#!/bin/sh -eu

for d in /src/*/; do
    [ -d "$d" ] || continue
    name=${d#/src/}
    name=${name%/}
    for sd in ${d}*; do
        cp --recursive --preserve=mode "$sd" "/srv/$name/"
    done
done
